import json
import os
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[2]
GOLDEN_PATH = ROOT / "config/golden/transition-domain.json"


class TestTransitionGoldenFixture(unittest.TestCase):
    def test_fixture_covers_every_required_domain_projection(self):
        if not GOLDEN_PATH.exists():
            self.skipTest("Phase-13 golden fixture is generated by the local PostgreSQL gate")
        payload = json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))
        self.assertEqual(payload["fixture_version"], "1")
        self.assertEqual(len(payload["source_sha256"]), 64)
        required = {
            "overview_totals", "country_totals", "programme_totals",
            "donor_rankings", "recipient_rankings", "organisation_details",
            "registry_search", "sankey", "currency_statuses", "score_components",
        }
        self.assertTrue(required.issubset(payload["semantic_contract"]))
        self.assertEqual(
            set(payload["non_database_journeys"]),
            {"news", "pipeline_status", "manual_refresh_permissions"},
        )


if __name__ == "__main__":
    unittest.main()
