"""Domain-sized repository interfaces for the PostgreSQL application runtime."""

from __future__ import annotations

from typing import Any, Mapping, Optional, Protocol, Sequence


class OrganizationReader(Protocol):
    async def list(self, **filters: Any) -> list[dict[str, Any]]: ...
    async def detail(self, organization_id: int) -> Optional[dict[str, Any]]: ...
    async def stats(self) -> dict[str, Any]: ...
    async def grants(self, organization_id: int, role: str) -> dict[str, Any]: ...
    async def sankey(
        self, organization_id: int, *, currency: Optional[str], limit: int
    ) -> dict[str, Any]: ...
    async def score(
        self, organization_id: int, target_profile: Optional[Mapping[str, Any]]
    ) -> dict[str, Any]: ...


class RegistryReader(Protocol):
    async def page(self, **filters: Any) -> dict[str, Any]: ...
    async def detail(self, registry_id: str) -> Optional[dict[str, Any]]: ...


class GrantAnalyticsReader(Protocol):
    async def beneficiary_geographies(self) -> list[str]: ...
    async def map(self, **filters: Any) -> dict[str, Any]: ...
    async def overview(self, **filters: Any) -> dict[str, Any]: ...
    async def suggestions(
        self, *, sources: Optional[Sequence[str]], limit: int
    ) -> dict[str, Any]: ...
    async def trends(self, **filters: Any) -> dict[str, Any]: ...
    async def drilldown(self, **filters: Any) -> dict[str, Any]: ...
    async def summary(self) -> dict[str, Any]: ...
    async def themes(self, *, currency: Optional[str]) -> dict[str, Any]: ...


class FunderRepository(Protocol):
    async def list(self, **filters: Any) -> dict[str, Any]: ...
    async def detail(self, source_funder_key: str, **filters: Any) -> Optional[dict[str, Any]]: ...
    async def reset(self, source_funder_key: str, *, actor_id: str) -> Optional[dict[str, Any]]: ...
    async def relink(
        self, source_funder_key: str, profile_id: int, *, actor_id: str
    ) -> Optional[dict[str, Any]]: ...
    async def queue_profile_cache(
        self, source_funder_key: str, *, actor_id: str, idempotency_key: str
    ) -> Optional[dict[str, Any]]: ...
    async def profile_cache(self, source_funder_key: str) -> Optional[dict[str, Any]]: ...


class JobRepository(Protocol):
    async def enqueue(
        self,
        job_type: str,
        payload: Mapping[str, Any],
        *,
        actor_id: str,
        idempotency_key: str,
    ) -> dict[str, Any]: ...
    async def latest_status(self) -> dict[str, Any]: ...
    async def history(self, *, limit: int) -> list[dict[str, Any]]: ...
    async def events(self, *, limit: int) -> list[dict[str, Any]]: ...
